spring.application.name=cemilac-iso
server.port=9002
server.servlet.context-path=/iso
server.tomcat.max-swallow-size=1024MB
server.tomcat.max-http-post-size=1024MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.fileSizeThreshold=1024MB
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
server.servlet.session.timeout=1800s
server.servlet.session.cookie.max-age=1800s
#server.servlet.session.timeout=30s
#server.servlet.session.cookie.max-age=30s
# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.main.allow-circular-references=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict
Referrer-Policy: same-origin
logging.level.root=INFO
logging.level.com.iso=INFO
logging.file.name=DA-ISO-app.log
logging.logback.rollingpolicy.file-name-pattern=da-iso-app-%d{dd-MM-yyyy-HH}_%i.log
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.max-history=10
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss} [%-5level][%-20logger{20}] %msg%n
logging.pattern.file=%d{dd-MM-yyyy HH:mm:ss} [%-5level][%-20logger{20}] %msg%n
# Download location
download.location=/home/da/Downloads/DownloadedData/
trusted.domains=http://localhost:9002,localhost,cemilac-project-backend.onrender.com
 


				  


