"<div class='popup' id='pop'>"
	 "<div class='box'>"
        "<img id='myimage' src='${pageContext.request.contextPath}/img/greentik.webp'>"
        "<h3 id='msg'></h3>"
         "<hr>"
        "<p id='intest' style=''color: red'></p>"
        "<button type='button' class='but' onclick='hide();'>Continue</button>"
    "</div>"
"</div>"